---
deployment:
  tasks:
    # Path where your live site should be served from
    - export DEPLOYPATH=/home/boxgra6/titus-duc.calisearch.org

    - /bin/echo "🔄 Starting Homelytics deployment..."

    # 1️⃣  Frontend build (Next.js)
    - cd /home/boxgra6/titus-duc.calisearch.org/app/frontend
    - /bin/echo "📦 Installing frontend dependencies..."
    - /bin/npm install
    - /bin/echo "🏗️  Building Next.js project..."
    - /bin/npm run build

    # (If you use `next export`, replace the copy command below with: cp -R out/* $DEPLOYPATH)
    - /bin/echo "🚚 Copying frontend build to deployment path..."
    - /bin/cp -R .next/static $DEPLOYPATH/.next/static
    - /bin/cp -R public/* $DEPLOYPATH/
    - /bin/cp package.json $DEPLOYPATH/

    # 2️⃣  Backend build (Go API)
    - cd /home/boxgra6/titus-duc.calisearch.org/app/backend
    - /bin/echo "⚙️  Building Go backend..."
    - /usr/bin/go build -o homelytics-api
    - /bin/mv homelytics-api $DEPLOYPATH/

    # 3️⃣  Final cleanup and permissions
    - /bin/echo "🧹 Cleaning temporary files..."
    - /bin/find $DEPLOYPATH -type f -name "*.log" -delete || true
    - /bin/chmod -R 755 $DEPLOYPATH

    - /bin/echo "✅ Homelytics deployment completed successfully!"
