---
deployment:
  tasks:
    # 📁 Set your public root folder (where the site is visible)
    - export DEPLOYPATH=/home/boxgra6/titus-duc.calisearch.org

    - /bin/echo "🚀 Starting Homelytics static deployment..."

    # 1️⃣ Frontend: build + export static site
    - cd /home/boxgra6/titus-duc.calisearch.org/app/frontend
    - /bin/echo "📦 Installing dependencies..."
    - /bin/npm install
    - /bin/echo "🏗️ Building and exporting static site..."
    - /bin/npm run build
    - /bin/npm run export

    # 2️⃣ Clear previous files (optional but cleaner)
    - /bin/echo "🧹 Cleaning old files from deployment path..."
    - /bin/find $DEPLOYPATH -mindepth 1 -maxdepth 1 ! -name '.well-known' ! -name 'cgi-bin' -exec rm -rf {} \;

    # 3️⃣ Copy new static build to live site root
    - /bin/echo "🚚 Copying new build to $DEPLOYPATH..."
    - /bin/cp -R out/* $DEPLOYPATH/

    - /bin/echo "✅ Homelytics static deployment completed successfully!"
