---
deployment:
  tasks:
    - export DEPLOYPATH=/home/boxgra6/titus-duc.calisearch.org

    - /bin/echo "🚀 Deploying Homelytics prebuilt static site..."

    # Clean the public root (keep SSL + cgi-bin)
    - /bin/find $DEPLOYPATH -mindepth 1 -maxdepth 1 ! -name '.well-known' ! -name 'cgi-bin' -exec rm -rf {} \;

    # Copy the locally-built site to public root
    - /bin/cp -R /home/boxgra6/titus-duc.calisearch.org/app/frontend/out/* $DEPLOYPATH/

    - /bin/echo "✅ Static site deployed successfully!"
